# Generated by Django 2.2.9 on 2020-07-12 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Apps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=5000)),
                ('slug', models.CharField(max_length=5000)),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='apps_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='apps_update_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'App',
                'verbose_name_plural': 'Apps',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Choices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=100)),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='choices_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='choices_update_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Choice',
                'verbose_name_plural': 'Choices',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Variables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('key', models.TextField(blank=True, null=True)),
                ('code', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='variables_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='variables_update_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Variable',
                'verbose_name_plural': 'Variables',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Models',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=50)),
                ('verbose_name', models.CharField(max_length=50)),
                ('verbose_name_plural', models.CharField(max_length=50)),
                ('django_modeladmin', models.BooleanField(default=False)),
                ('django_tabularinline', models.BooleanField(default=False)),
                ('rendered_model', models.TextField(blank=True, null=True)),
                ('rendered_form', models.TextField(blank=True, null=True)),
                ('rendered_admin', models.TextField(blank=True, null=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='models_models', to='dag.Apps')),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='models_created_by', to=settings.AUTH_USER_MODEL)),
                ('inline_models', models.ManyToManyField(blank=True, related_name='models_models', to='dag.Models')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='models_update_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Model',
                'verbose_name_plural': 'Models',
                'ordering': ['app', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ModelFunctions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=500)),
                ('slug', models.CharField(max_length=500)),
                ('code', models.TextField()),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='modelfunctions_created_by', to=settings.AUTH_USER_MODEL)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='modelfunctions_model', to='dag.Models')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='modelfunctions_update_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Model Function',
                'verbose_name_plural': 'Model Functions',
                'ordering': ['model', 'title'],
            },
        ),
        migrations.CreateModel(
            name='FieldTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=100)),
                ('model_code', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fieldtypes_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fieldtypes_update_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Field Type',
                'verbose_name_plural': 'Field Type',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Fields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=50)),
                ('slug', models.CharField(max_length=50)),
                ('help_text', models.CharField(max_length=200)),
                ('max_length', models.IntegerField(blank=True, null=True)),
                ('default_value', models.CharField(blank=True, max_length=50, null=True)),
                ('is_null', models.BooleanField(default=False)),
                ('is_blank', models.BooleanField(default=False)),
                ('is_unique', models.BooleanField(default=False)),
                ('is_readonly', models.BooleanField(default=False)),
                ('is_editable', models.BooleanField(default=False)),
                ('is_db_index', models.BooleanField(default=False)),
                ('is_ordering', models.BooleanField(default=False)),
                ('order', models.IntegerField()),
                ('is_model_title', models.BooleanField(default=False)),
                ('in_search_fields', models.BooleanField(default=False)),
                ('in_list_filter', models.BooleanField(default=False)),
                ('in_list_display', models.BooleanField(default=False)),
                ('in_field_model', models.BooleanField(default=False)),
                ('rendered_model_django', models.TextField(blank=True, null=True)),
                ('rendered_form_django', models.TextField(blank=True, null=True)),
                ('rendered_table_html', models.TextField(blank=True, null=True)),
                ('rendered_form_html', models.TextField(blank=True, null=True)),
                ('rendered_filter_html', models.TextField(blank=True, null=True)),
                ('rendered_filter_dict', models.TextField(blank=True, null=True)),
                ('choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fields_choices', to='dag.Choices')),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fields_created_by', to=settings.AUTH_USER_MODEL)),
                ('field_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fields_field_types', to='dag.FieldTypes')),
                ('foreignkey', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fields_foreignkey', to='dag.Models')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fields_models', to='dag.Models')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fields_update_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Field',
                'verbose_name_plural': 'Fields',
                'ordering': ['model', 'order'],
            },
        ),
        migrations.CreateModel(
            name='CustomModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=100)),
                ('model_code', models.TextField(blank=True, null=True)),
                ('admin_code', models.TextField(blank=True, null=True)),
                ('form_code', models.TextField(blank=True, null=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='custommodels_app', to='dag.Apps')),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='custommodels_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='custommodels_update_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Custom Model',
                'verbose_name_plural': 'Custom Models',
                'ordering': ['app', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ChoicesValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('key', models.CharField(max_length=5000)),
                ('value', models.CharField(max_length=5000)),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='choicesvalues_choices', to='dag.Choices')),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='choicesvalues_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='choicesvalues_update_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Choice Value',
                'verbose_name_plural': 'Choice Values',
                'ordering': ['choice', 'key'],
            },
        ),
    ]
