# Generated by Django 2.2.13 on 2020-07-12 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dag', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='models',
            name='django_tabularinline',
        ),
        migrations.AlterField(
            model_name='models',
            name='django_modeladmin',
            field=models.BooleanField(default=True),
        ),
    ]
