# Generated by Django 2.2.19 on 2021-03-08 18:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dag', '0002_auto_20210307_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessRules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('app_title', models.CharField(max_length=200)),
                ('model_title', models.CharField(max_length=200)),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='businessrules_created_by', to=settings.AUTH_USER_MODEL)),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='businessrules_model', to='dag.Models')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='businessrules_update_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Business Rule',
                'verbose_name_plural': 'Business Rules',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='BusinessRulesCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('func', models.CharField(choices=[('MODEL_SAVE', 'MODEL_SAVE'), ('FORM_INIT', 'FORM_INIT'), ('FORM_CLEAN', 'FORM_CLEAN'), ('ADMIN_CUSTOM_FILTER', 'ADMIN_CUSTOM_FILTER'), ('ADMIN_CUSTOM_COLUMN', 'ADMIN_CUSTOM_COLUMN')], max_length=30)),
                ('code', models.TextField(blank=True, null=True)),
                ('business_rule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='businessrulescode_business_rule', to='dag.BusinessRules')),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='businessrulescode_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='businessrulescode_update_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Business Rule',
                'verbose_name_plural': 'Business Rules',
                'ordering': ['title'],
            },
        ),
    ]
