# Generated by Django 2.2.19 on 2021-03-21 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dag', '0004_models_django_inline_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='models',
            name='django_inline_type',
        ),
        migrations.RemoveField(
            model_name='models',
            name='django_modeladmin',
        ),
        migrations.AddField(
            model_name='models',
            name='is_read_only',
            field=models.BooleanField(default=False),
        ),
    ]
