# Generated by Django 2.2.19 on 2021-03-21 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dag', '0005_auto_20210321_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='models',
            name='is_model_admin',
            field=models.BooleanField(default=False),
        ),
    ]
