# Generated by Django 2.2.19 on 2021-03-21 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dag', '0006_models_is_model_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='models',
            name='is_model_admin',
            field=models.BooleanField(default=True),
        ),
    ]
