# Generated by Django 2.2.19 on 2021-03-21 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dag', '0007_auto_20210321_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='models',
            name='inline_models',
        ),
        migrations.CreateModel(
            name='ModelsInline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('type_inline', models.CharField(default='TabularInline', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='modelsinline_created_by', to=settings.AUTH_USER_MODEL)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelsinline_model', to='dag.Models')),
                ('model_inline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelsinline_model_inline', to='dag.Models')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='modelsinline_update_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inline Model',
                'verbose_name_plural': 'Inline Models',
                'ordering': ['model', 'model_inline', 'type_inline'],
                'unique_together': {('model', 'model_inline', 'type_inline')},
            },
        ),
    ]
