# Generated by Django 3.2 on 2022-03-25 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dag', '0008_auto_20210321_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fields',
            name='fieldtype',
        ),
        migrations.DeleteModel(
            name='FieldTypes',
        ),
    ]
